#!/usr/bin/env python 
# -*- coding:utf-8 -*-

# 这里设置必须是int类型的
CAN_KIND_USBCAN2 = 4
CAN_KIND_USBCAN_2E_U = 21
CAN_KIND_USBCAN_4E_U = 31
CAN_KIND_USBCAN_8E_U = 34

CAN_KIND_USBCAN2_NAME = 'USBCAN2'
CAN_KIND_USBCAN_2E_U_NAME = 'USBCAN_2E_U'
CAN_KIND_USBCAN_4E_U_NAME = 'USBCAN_4E_U'
CAN_KIND_USBCAN_8E_U_NAME = 'USBCAN_8E_U'
